INSERT INTO COUNTRY VALUES ( 1,'ARGENTINA');

INSERT INTO COUNTRY VALUES ( 2,'BRASIL');

INSERT INTO PROVINCE 
VALUES 	(	1,'BUENOS AIRES',	1),
		(	2,'CORDOBA'		,	1);
        
INSERT INTO CITY
VALUES	(	1,'CABALLITO'	,	1),
		(	2,'MORON'		,	1),
        (	3,'SAN JUSTO'	,	1);